server:
  port: 9191
spring:
  application:
    name: ORDER-SERVICE
# h2:
#   console:
#     enabled: true
logging:
  file:
    name: C:Users/reece/Desktop/logs/microservices.log
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#  cloud:
#    config:
#      uri:
#        - http://localhost:9196